"""inicial

Revision ID: c31872e3a7c5
Revises: 
Create Date: 2024-09-23 14:27:55.787559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31872e3a7c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('cod_game', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cod_game')
    )
    op.create_table('habilities',
    sa.Column('cod_ability', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cod_ability')
    )
    op.create_table('locations',
    sa.Column('cod_location', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cod_location')
    )
    op.create_table('moves',
    sa.Column('cod_move', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cod_move')
    )
    op.create_table('pokemons',
    sa.Column('cod_pokemon', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cod_pokemon')
    )
    op.create_table('pokemon_games',
    sa.Column('cod_pokemon_game', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_cod', sa.Integer(), nullable=False),
    sa.Column('game_cod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_cod'], ['games.cod_game'], ),
    sa.ForeignKeyConstraint(['pokemon_cod'], ['pokemons.cod_pokemon'], ),
    sa.PrimaryKeyConstraint('cod_pokemon_game')
    )
    op.create_table('pokemon_habilities',
    sa.Column('cod_pokemon_ability', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_cod', sa.Integer(), nullable=False),
    sa.Column('ability_cod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_cod'], ['habilities.cod_ability'], ),
    sa.ForeignKeyConstraint(['pokemon_cod'], ['pokemons.cod_pokemon'], ),
    sa.PrimaryKeyConstraint('cod_pokemon_ability')
    )
    op.create_table('pokemon_locations',
    sa.Column('cod_pokemon_location', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_cod', sa.Integer(), nullable=False),
    sa.Column('location_cod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_cod'], ['locations.cod_location'], ),
    sa.ForeignKeyConstraint(['pokemon_cod'], ['pokemons.cod_pokemon'], ),
    sa.PrimaryKeyConstraint('cod_pokemon_location')
    )
    op.create_table('pokemon_moves',
    sa.Column('cod_pokemon_move', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_cod', sa.Integer(), nullable=False),
    sa.Column('move_cod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_cod'], ['moves.cod_move'], ),
    sa.ForeignKeyConstraint(['pokemon_cod'], ['pokemons.cod_pokemon'], ),
    sa.PrimaryKeyConstraint('cod_pokemon_move')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_moves')
    op.drop_table('pokemon_locations')
    op.drop_table('pokemon_habilities')
    op.drop_table('pokemon_games')
    op.drop_table('pokemons')
    op.drop_table('moves')
    op.drop_table('locations')
    op.drop_table('habilities')
    op.drop_table('games')
    # ### end Alembic commands ###
